name: release
on:
  push:
    tags:
      - '*'

env:
  HANDOUT_ARTIFACT_NAME: 25_sez_solid_handout
  SLIDES_ARTIFACT_NAME: 25_sez_solid_presentation

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  release:
      runs-on: ubuntu-latest
      needs: [ build ]
      permissions:
        contents: write
      steps:
        - name: Download slides artifact
          uses: actions/download-artifact@v4
          with:
            pattern: ${{ env.SLIDES_ARTIFACT_NAME }}

        - name: Download article artifact
          uses: actions/download-artifact@v4
          with:
            pattern: ${{ env.HANDOUT_ARTIFACT_NAME }}
          
        - name: Create release
          uses: ncipollo/release-action@v1.14.0
          with:
            artifacts: ${{ env.SLIDES_ARTIFACT_NAME }}/*, ${{ env.HANDOUT_ARTIFACT_NAME }}/*
            body: "Release of version ${{ github.ref_name }}"
            allowUpdates: true
